/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clientDBMysql;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException; 
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.text.MessageFormat;
import java.util.Vector;


/**
 *
 * @author pi
 */
public class clientDBMysql extends javax.swing.JFrame {

    private static final String username = "alejandro";
    private static final String password = "lexi2020";
    private static final String dataConn = "jdbc:mysql://localhost:3306/clientData";
    
    Connection sqlConn = null;
    PreparedStatement pst = null;
        ResultSet  rs = null;
    
    /**
     * Creates new form clientDBMysql
     */
    public clientDBMysql() {
        initComponents();
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    /**************************************************************************/
    
    public void updateTable(){
        int q;
        try {
            
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn,username,password);
            pst = sqlConn.prepareStatement("select * from clientData");
            
            rs = pst.executeQuery();
            ResultSetMetaData clData = rs.getMetaData ();
            
            q = clData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)dataTable.getModel();
            RecordTable.setRowCount(0);
            
            while(rs.next()){
                Vector columnData = new Vector();
                
                for (int i = 1; i <= q; i++){
                    columnData.add(rs.getString("id"));
                    columnData.add(rs.getString("clientID"));
                    columnData.add(rs.getString("firstName"));
                    columnData.add(rs.getString("lastName"));
                    columnData.add(rs.getString("phoneNumber"));
                    columnData.add(rs.getString("email"));
                    columnData.add(rs.getString("streetAddress"));
                    columnData.add(rs.getString("city"));
                    columnData.add(rs.getString("state"));
                    columnData.add(rs.getString("zipCode"));
                    columnData.add(rs.getString("priority"));
                }
                
                RecordTable.addRow(columnData);
                    
            }
            
            
            
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    public void resetFields(){
        textClientID.setText("");
        textFirstName.setText("");
        textLastName.setText("");
        textPhoneNum.setText("");
        textEmail.setText("");
        textStreet.setText("");
        textCity.setText("");
        comboBoxState.setSelectedIndex(0);
        textZip.setText("");
        comboBoxPriority.setSelectedIndex(0);
    }
    
    
    /**************************************************************************/
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        textClientID = new javax.swing.JTextField();
        textFirstName = new javax.swing.JTextField();
        textLastName = new javax.swing.JTextField();
        textPhoneNum = new javax.swing.JTextField();
        textEmail = new javax.swing.JTextField();
        textStreet = new javax.swing.JTextField();
        textCity = new javax.swing.JTextField();
        textZip = new javax.swing.JTextField();
        comboBoxPriority = new javax.swing.JComboBox<>();
        comboBoxState = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnAddNew = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 4, true));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Email");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 140, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Client ID");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Last Name");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 140, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Phone Number");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 160, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Street Address");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 160, 30));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("City");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 140, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setText("State");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 140, 30));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setText("Zip Code");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 140, 30));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setText("Priority");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 140, 30));
        jPanel6.add(textClientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 240, 30));
        jPanel6.add(textFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 240, 30));
        jPanel6.add(textLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 240, 30));
        jPanel6.add(textPhoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 240, 30));
        jPanel6.add(textEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 240, 30));
        jPanel6.add(textStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 240, 30));
        jPanel6.add(textCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 240, 30));
        jPanel6.add(textZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 240, 30));

        comboBoxPriority.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Low", "Normal", "Important", "Critical" }));
        comboBoxPriority.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxPriorityActionPerformed(evt);
            }
        });
        jPanel6.add(comboBoxPriority, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 240, 30));

        comboBoxState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AL", "AK", "AZ", "AR", "CA", "C", "CO", "CT", "DE", "DC", "FL", "GA", "GU", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "PR", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VI", "VA", "WA", "WV", "WI", "WY" }));
        comboBoxState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxStateActionPerformed(evt);
            }
        });
        jPanel6.add(comboBoxState, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 240, 30));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setText("First Name");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 140, 30));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 510, 540));

        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 4, true));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Client ID", "firstName", "lastName", "phoneNumber", "email", "streetAddress", "city", "state", "zipCode", "priority"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        dataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dataTable);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 740, 480));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 800, 540));

        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 4, true));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExit.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel8.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 10, 200, 50));

        btnAddNew.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnAddNew.setText("Add New");
        btnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewActionPerformed(evt);
            }
        });
        jPanel8.add(btnAddNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 200, 50));

        btnUpdate.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel8.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 200, 50));

        btnReset.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel8.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 200, 50));

        btnDelete.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel8.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 200, 50));

        btnPrint.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel8.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 200, 50));

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 1320, 70));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 1360, 660));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setText("Client Database Management System ");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 1040, 60));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1360, 90));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        DefaultTableModel RecordTable = (DefaultTableModel)dataTable.getModel();
            int SelectedRows = dataTable.getSelectedRow();
            
            try {
                int id = Integer.parseInt(RecordTable.getValueAt(SelectedRows, 0).toString());
                
                int deleteItem = JOptionPane.showConfirmDialog(null, "Confirm item deletion", "Warning", JOptionPane.YES_NO_OPTION);
                if (deleteItem == JOptionPane.YES_OPTION){
                    
                    Class.forName("com.mysql.jdbc.Driver");
                    sqlConn = DriverManager.getConnection(dataConn,username,password);
                    pst = sqlConn.prepareStatement("delete from clientData where id = ?");
                    
                    pst.setInt(1, id);
                    pst.executeUpdate();
                    
                    JOptionPane.showMessageDialog(this, "Client Data Removed");
                    updateTable();
                    resetFields();
                    
                }
            } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clientDBMysql.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(clientDBMysql.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        MessageFormat header = new MessageFormat("Client Data");
        MessageFormat footer = new MessageFormat("Page {0, number, integer}");
        
        try {
            dataTable.print(JTable.PrintMode.NORMAL,header,footer);
            
        } catch (java.awt.print.PrinterException e){
            System.err.format("No Printer Found", e.getMessage());
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        DefaultTableModel RecordTable = (DefaultTableModel)dataTable.getModel();
        int SelectedRows = dataTable.getSelectedRow();
        
        try {
            
            int id = Integer.parseInt(RecordTable.getValueAt(SelectedRows, 0).toString());
            
            Class.forName("com.mysql.jdbc.Driver");
                sqlConn = DriverManager.getConnection(dataConn, username, password);
                    pst = sqlConn.prepareStatement("update clientData set clientID = ?,firstName = ?, lastName = ?, phoneNumber = ?,"
                            + "email = ?,streetAddress = ?,city = ?,state = ?,zipCode = ?,priority = ?"
                            + "where id = ?");
                    
                    pst.setString(1, textClientID.getText());
                    pst.setString(2, textFirstName.getText());
                    pst.setString(3, textLastName.getText());
                    pst.setString(4, textPhoneNum.getText());
                    pst.setString(5, textEmail.getText());
                    pst.setString(6, textStreet.getText());
                    pst.setString(7, textCity.getText());
                    pst.setString(8, (String) comboBoxState.getSelectedItem());
                    pst.setString(9, textZip.getText());
                    pst.setString(10, (String) comboBoxPriority.getSelectedItem());
                    pst.setInt(11, id);
                    
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Client Data Updated");
                    updateTable();
                
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clientDBMysql.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(clientDBMysql.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void comboBoxPriorityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxPriorityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxPriorityActionPerformed

    private void comboBoxStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxStateActionPerformed
    private JFrame frame;
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Are you sure you would like to exit?", "Client Management", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
        try {
            
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn,username,password);
            pst = sqlConn.prepareStatement("insert into clientData(clientID, firstName, lastName, phoneNumber, email, streetAddress, city, state, zipCode, priority)values"
                    + "(?,?,?,?,?,?,?,?,?,?)");
            
            pst.setString(1, textClientID.getText());
            pst.setString(2, textFirstName.getText());
            pst.setString(3, textLastName.getText());
            pst.setString(4, textPhoneNum.getText());
            pst.setString(5, textEmail.getText());
            pst.setString(6, textStreet.getText());
            pst.setString(7, textCity.getText());
            pst.setString(8, (String) comboBoxState.getSelectedItem());
            pst.setString(9, textZip.getText());
            pst.setString(10, (String) comboBoxPriority.getSelectedItem());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Client Data Submitted");
            
            updateTable();
            resetFields();
            
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clientDBMysql.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(clientDBMysql.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddNewActionPerformed

    private void dataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataTableMouseClicked
        DefaultTableModel RecordTable = (DefaultTableModel)dataTable.getModel();
        int SelectedRows = dataTable.getSelectedRow();
        
        textClientID.setText(RecordTable.getValueAt(SelectedRows,1).toString());
        textFirstName.setText(RecordTable.getValueAt(SelectedRows,2).toString());
        textLastName.setText(RecordTable.getValueAt(SelectedRows,3).toString());
        textPhoneNum.setText(RecordTable.getValueAt(SelectedRows,4).toString());
        textEmail.setText(RecordTable.getValueAt(SelectedRows,5).toString());
        textStreet.setText(RecordTable.getValueAt(SelectedRows,6).toString());
        textCity.setText(RecordTable.getValueAt(SelectedRows,7).toString());
        comboBoxState.setSelectedItem(RecordTable.getValueAt(SelectedRows,8).toString());
        textZip.setText(RecordTable.getValueAt(SelectedRows,9).toString());
        comboBoxPriority.setSelectedItem(RecordTable.getValueAt(SelectedRows,10).toString());
       
    }//GEN-LAST:event_dataTableMouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        
        resetFields();
        
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clientDBMysql.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clientDBMysql.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clientDBMysql.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clientDBMysql.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clientDBMysql().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> comboBoxPriority;
    private javax.swing.JComboBox<String> comboBoxState;
    private javax.swing.JTable dataTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField textCity;
    private javax.swing.JTextField textClientID;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textFirstName;
    private javax.swing.JTextField textLastName;
    private javax.swing.JTextField textPhoneNum;
    private javax.swing.JTextField textStreet;
    private javax.swing.JTextField textZip;
    // End of variables declaration//GEN-END:variables
}
